-- Criacao do banco e estrutura das tabelas

CREATE DATABASE banco_clientes;

CREATE TABLE CIDADE (
    ID_CIDADE INTEGER NOT NULL,
    NOME VARCHAR(30),
    CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE)
);

CREATE TABLE CONTA (
    ID_CONTA INTEGER NOT NULL,
    SALDO DOUBLE PRECISION,
    CONSTRAINT PK_CONTA PRIMARY KEY (ID_CONTA)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INTEGER NOT NULL,
    NOME VARCHAR(30),
    ID_CIDADE INTEGER,
    ID_CONTA INTEGER,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT FK_CIDADE FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE),
    CONSTRAINT FK_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA (ID_CONTA)
);
